# Dependencies
markdown:         redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            me link
tagline:          'API文档'
description:      '表情me link API(简称me link)是由上海似颜绘科技有限公司开发的国内首款在线卡通形象与动态表情定制接口平台.'
url:              http://apidoc.stampmeapp.com

author:
  name:           'Min Chen'
  url:            https://github.com/mchenla

paginate:         5

# Custom vars
version:          0.5.9

github:
  repo:           https://github.com/siyanhui/melink
